[package]
name = "threads_demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "matrix"
path = "src/matrix.rs"

[[bin]]
name = "encryptor"
path = "src/encryptor.rs"

[dependencies]
rayon = "1"
aes-gcm = "0.10"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
walkdir = "2"
